<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>7d0f0abe-a0c1-42ca-86f0-6271534afa68</groupId>
		<artifactId>paradiso-parent-pom</artifactId>
		<version>1.0.0</version>
	</parent>
	<groupId>29ed4528-e3f3-4e00-a045-77cbb577676c</groupId>
	<artifactId>sys-sales</artifactId>
	<version>1.0.0</version>
	<packaging>mule-application</packaging>

	<name>sys-sales</name>

	<description/>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<app.runtime>4.11.0</app.runtime>
		<tags/>
		<categories>[]</categories>
		<fields>[]</fields>
		<mule.maven.plugin.version>4.7.0</mule.maven.plugin.version>
	</properties>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.2.0</version>
			</plugin>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<classifier>mule-application</classifier>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>29ed4528-e3f3-4e00-a045-77cbb577676c</groupId>
			<artifactId>sales-system-api</artifactId>
			<version>1.0.1</version>
			<classifier>raml</classifier>
			<type>zip</type>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
	</repositories>

</project>
